In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
test = pd.read_csv("enigma_dataset.csv")
test.head(50)

,Occupational_Category,Number_of_Full_Time_Year_Round_Workers_Total_Estimate,Number_of_Full_Time_Year_Round_Workers_Total_MOE,Number_of_Full_Time_Year_Round_Workers_Men_Estimate,Number_of_Full_Time_Year_Round_Workers_Men_MOE,Number_of_Full_Time_Year_Round_Workers_Women_Estimate,Number_of_Full_Time_Year_Round_Workers_Women_MOE,Percentage_of_Women_in_Occupational_Category_Estimate,Percentage_of_Women_in_Occupational_Category_MOE,Median_Earnings_In_Dollars_Total_Estimate,Median_Earnings_In_Dollars_Total_MOE,Median_Earnings_In_Dollars_Men_Estimate,Median_Earnings_In_Dollars_Men_MOE,Median_Earnings_In_Dollars_Women_Estimate,Median_Earnings_In_Dollars_Women_MOE,Womens_Earnings_As_A_Percentage_of_Mens_Earnings_Estimate,Womens_Earnings_As_A_Percentage_of_Mens_Earnings_MOE
0,Total,106609098,133999,60708461,96733,45900637,88317,43.055084,0.1,45860,66,50741,54,40675,54,80.2,0.1
1,"Management, Business, Science, and Arts Occupa...",44274859,130437,22578160,79447,21696699,82092,49.004558,0.1,65004,161,76692,155,55474,144,72.3,0.3
2,"Management, Business, and Financial Occupations",19812917,75230,11195064,55370,8617853,46676,43.496134,0.2,70602,135,80473,201,60751,124,75.5,0.2
3,Management Occupations,13689475,62435,8380083,44079,5309392,40577,38.784482,0.2,73688,473,81829,235,62254,175,76.1,0.3
4,Chief executives,1068258,17593,813898,14815,254360,7288,23.810727,0.6,130266,1910,141108,1375,103564,4259,73.39342915,3.1
5,General and operations managers,834005,12760,588111,9849,245894,8348,29.483516,0.9,70686,627,76246,776,56906,1111,74.63473494,1.6
6,Legislators,13966,1709,7431,1235,6535,1456,46.792210,8.7,65592,5454,67233,12792,63788,10085,94.87602814,23.5
7,Advertising and promotions managers,42996,3032,17752,1984,25244,2262,58.712438,3.2,67082,3498,79594,6833,61173,3088,76.8562957,7.7
8,Marketing and sales managers,843840,15667,464995,10519,378845,10042,44.895359,0.8,82357,1263,100137,1477,69079,2413,68.98449125,2.6
9,Public relations and fundraising managers,51121,3755,16705,1963,34416,3046,67.322627,3.3,77835,4128,84016,7323,75260,3792,89.57817559,9
10,Administrative services managers,136431,5932,82550,4394,53881,4158,39.493224,2.5,64208,1927,69788,3102,60177,1731,86.2282914,4.6
11,Computer and information systems managers,564747,10510,413250,9263,151497,5243,26.825641,0.8,103513,1960,107411,1908,95603,2703,89.00671253,3
12,Financial managers,1067163,18404,506068,10743,561095,14469,52.578191,1.0,76178,753,100505,689,62089,579,61.77702602,0.7
13,Compensation and benefits managers,17074,2352,4254,1016,12820,1928,75.084924,4.5,71605,4679,93895,15621,70251,5258,(X),(X)
14,Human resources managers,369518,9073,143842,5734,225676,7354,61.073074,1.3,72008,801,77463,4593,70342,1351,90.80722409,5.7
15,Training and development managers,49960,3854,23959,2914,26001,3042,52.043635,4.6,72153,4805,82392,7206,64686,5535,78.51004952,9.6
16,Industrial production managers,220263,7532,176191,6559,44072,3231,20.008808,1.3,76077,1099,77262,1807,70073,4005,90.69529652,5.6
17,Purchasing managers,181255,6560,94445,5029,86810,4236,47.893851,1.6,76501,1625,82307,2505,70023,2812,85.07538848,4.3
18,"Transportation, storage, and distribution mana...",222794,7309,182671,7383,40123,3402,18.009013,1.4,52485,1573,52318,1091,54796,3599,104.7364196,7.2
19,"Farmers, ranchers, and other agricultural mana...",451680,9794,400989,9109,50691,3094,11.222768,0.6,41404,525,42190,737,30405,1257,72.06684048,3.2
20,Construction managers,573250,12237,528329,11869,44921,3637,7.836197,0.6,71331,693,71907,803,62218,3121,86.52565119,4.4
21,Education administrators,747962,12539,282062,8717,465900,8797,62.289261,0.5,70748,476,80380,827,64509,1589,80.25503857,2.1
22,Architectural and engineering managers,144812,5961,131956,5939,12856,1857,8.877717,1.2,130293,2326,130300,2512,130255,6336,99.96546431,5.2
23,Food service managers,792807,16772,436773,11837,356034,11181,44.908029,1.0,38380,1296,42601,1510,31861,485,74.78932419,2.9
24,Funeral service managers,5733,1040,4173,921,1560,516,27.210884,7.5,60848,6112,60487,8583,61597,10890,(X),(X)
25,Gaming managers,15477,1758,10129,1417,5348,1170,34.554500,6.5,55674,5819,56664,8926,52872,6227,93.30792037,18.4
26,Lodging managers,107568,5734,50893,3792,56675,4558,52.687602,3.2,45875,1807,51697,1832,41285,1145,79.85956632,3.6
27,Medical and health services managers,606615,11531,176012,6730,430603,9999,70.984562,0.9,71739,750,87311,3047,66855,876,76.57110788,2.9
28,Natural sciences managers,17916,1981,8464,1527,9452,1392,52.757312,5.1,92161,11812,111817,10376,76768,9964,68.65503457,11
29,Postmasters and mail superintendents,20947,2406,11398,1820,9549,1304,45.586480,3.4,71429,948,72401,3138,67745,4019,93.5691496,6.9
30,"Property, real estate, and community associati...",459115,10712,233710,7103,225405,7807,49.095543,1.3,51957,590,61797,1225,46405,788,75.09264204,2
31,Social and community service managers,296269,8924,91027,4183,205242,7693,69.275557,1.5,56610,773,68388,3529,52444,1006,76.6859683,4.2
32,Emergency management directors,7304,1388,5663,1319,1641,599,22.467141,7.0,68834,6104,68407,7074,70337,23709,(X),(X)
33,"Managers, all other",3758629,31438,2472383,25093,1286246,18609,34.221148,0.4,78843,1058,84600,1380,67769,1311,80.10520095,2
34,Business and Financial Operations Occupations,6123442,37510,2814981,29961,3308461,25111,54.029433,0.3,63511,458,74011,863,56897,298,76.9,1
35,"Agents and business managers of artists, perfo...",33337,3818,17328,2356,16009,2227,48.021718,3.8,51728,2495,55328,7454,50761,3937,91.74558994,14.3
36,"Buyers and purchasing agents, farm products",7795,1301,5584,1047,2211,750,28.364336,8.4,66349,4797,69214,7849,57352,12767,(X),(X)
37,"Wholesale and retail buyers, except farm products",139871,6122,71088,4447,68783,4294,49.176026,2.2,41625,876,41612,1574,41637,1247,100.0600788,4.8
38,"Purchasing agents, except wholesale, retail, a...",253717,7897,122410,5830,131307,5213,51.753331,1.3,54740,1558,60366,989,51121,620,84.68508763,1.7
39,"Claims adjusters, appraisers, examiners, and i...",271129,9435,105531,5150,165598,7308,61.077199,1.7,52582,1135,60840,870,50024,966,82.22222222,2
40,Compliance officers,226344,7585,107204,5395,119140,5702,52.636695,1.8,69262,2222,73211,3041,64588,2074,88.22171532,4.6
41,Cost estimators,122804,5612,105522,5415,17282,1900,14.072831,1.4,63106,1804,65805,1115,49752,3618,75.60519717,5.6
42,Human resources workers,678049,13678,188438,7495,489611,11789,72.208793,0.9,57369,884,66412,1923,54975,1061,82.77871469,2.9
43,"Compensation, benefits, and job analysis speci...",47978,3563,10731,1783,37247,3095,77.633499,2.9,54108,3093,62886,6056,51522,1426,81.92920523,8.2
44,Training and development specialists,111303,5046,50284,3499,61019,3700,54.822422,2.2,58739,3093,65332,3572,52456,2925,80.29143452,6.3
45,Logisticians,117328,4387,77464,3784,39864,3154,33.976544,2.4,52260,1148,55233,1921,50220,1476,90.92390419,4.1
46,Management analysts,630863,11588,369877,8099,260986,8942,41.369679,1.2,83080,1848,91169,977,76338,975,83.73240904,1.4
47,"Meeting, convention, and event planners",96349,5575,24116,2970,72233,4805,74.970161,2.5,46598,1026,42729,4863,47221,1374,110.5127665,13
48,Fundraisers,68581,3864,20709,2101,47872,3118,69.803590,2.3,66048,1339,77186,9364,64272,2599,83.2689866,10.6
49,Market research analysts and marketing special...,237008,8119,103644,5151,133364,5503,56.269831,1.3,70985,993,82565,4481,64398,2652,77.99672985,5.3

In [8]:
test.columns

Index(['DEPARTMENT', 'DESCR', 'GENDER DESCR', 'Admin Support # EE',
       'Admin Support % Gender', 'Admin Support Avg Hrly',
       'Admin Support Avg Yrs in Current Job', 'Officials/Admin # EE',
       'Officials/Admin % Gender', 'Officials/Admin Avg Hrly',
       'Officials/Admin Avg Yrs in Current Job', 'Para-Professionals # EE',
       'Para-Professionals % Gender', 'Para-Professionals Avg Hrly',
       'Para-Professionals Avg Yrs in Current Job', 'Professionals # EE',
       'Professionals % Gender', 'Professionals Avg Hrly',
       'Professionals Avg Yrs in Current Job', 'Protected Services # EE',
       'Protected Services % Gender', 'Protected Services Avg Hrly',
       'Protected Services Avg Yrs in Current Job', 'Service/Maintenance # EE',
       'Service/Maintenance % Gender', 'Service/Maintenance Avg Hrly',
       'Service/Maintenance Avg Yrs in Current Job', 'Skilled Craft # EE',
       'Skilled Craft % Gender', 'Skilled Craft Avg Hrly',
       'Skilled Craft Avg Yrs in Current Job', 'Technicians # EE',
       'Technicians % Gender', 'Technicians Avg Hrly',
       'Technicians Avg Yrs in Current Job'],
      dtype='object')

In [18]:
selected_test = test[['Occupational_Category','Percentage_of_Women_in_Occupational_Category_Estimate','Womens_Earnings_As_A_Percentage_of_Mens_Earnings_Estimate']]
selected_test['Womens_Earnings_As_A_Percentage_of_Mens_Earnings_Estimate'] = selected_test['Womens_Earnings_As_A_Percentage_of_Mens_Earnings_Estimate'].replace({"(X)": None})
selected_test

/usr/local/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Occupational_Category,Percentage_of_Women_in_Occupational_Category_Estimate,Womens_Earnings_As_A_Percentage_of_Mens_Earnings_Estimate
0,Total,43.055084,80.2
1,"Management, Business, Science, and Arts Occupa...",49.004558,72.3
2,"Management, Business, and Financial Occupations",43.496134,75.5
3,Management Occupations,38.784482,76.1
4,Chief executives,23.810727,73.39342915
5,General and operations managers,29.483516,74.63473494
6,Legislators,46.792210,94.87602814
7,Advertising and promotions managers,58.712438,76.8562957
8,Marketing and sales managers,44.895359,68.98449125
9,Public relations and fundraising managers,67.322627,89.57817559
10,Administrative services managers,39.493224,86.2282914
11,Computer and information systems managers,26.825641,89.00671253
12,Financial managers,52.578191,61.77702602
13,Compensation and benefits managers,75.084924,None
14,Human resources managers,61.073074,90.80722409
15,Training and development managers,52.043635,78.51004952
16,Industrial production managers,20.008808,90.69529652
17,Purchasing managers,47.893851,85.07538848
18,"Transportation, storage, and distribution mana...",18.009013,104.7364196
19,"Farmers, ranchers, and other agricultural mana...",11.222768,72.06684048
20,Construction managers,7.836197,86.52565119
21,Education administrators,62.289261,80.25503857
22,Architectural and engineering managers,8.877717,99.96546431
23,Food service managers,44.908029,74.78932419
24,Funeral service managers,27.210884,None
25,Gaming managers,34.554500,93.30792037
26,Lodging managers,52.687602,79.85956632
27,Medical and health services managers,70.984562,76.57110788
28,Natural sciences managers,52.757312,68.65503457
29,Postmasters and mail superintendents,45.586480,93.5691496
...,...,...,...
528,Taxi drivers and chauffeurs,12.118453,87.07518023
529,"Motor vehicle operators, all other",15.031187,None
530,Locomotive engineers and operators,5.097396,None
531,"Railroad brake, signal, and switch operators",6.642274,None
532,Railroad conductors and yardmasters,5.977926,None
533,"Subway, streetcar, and other rail transportati...",12.803394,None
534,Sailors and marine oilers,10.321733,None
535,Ship and boat captains and operators,4.460055,None
536,Ship engineers,10.343688,None
537,Bridge and lock tenders,8.813818,None
538,Parking lot attendants,13.058546,None
539,Automotive and watercraft service attendants,11.907016,None
540,Transportation inspectors,12.593002,None
541,"Transportation attendants, except flight atten...",51.876155,None
542,Other transportation workers,16.978525,None
543,Material Moving Occupations,18.811464,79.2
544,Conveyor operators and tenders,22.136887,None
545,Crane and tower operators,2.824134,None
546,"Dredge, excavating, and loading machine operators",1.402628,None
547,Hoist and winch operators,3.420964,None
548,Industrial truck and tractor operators,7.187780,99.89784863
549,Cleaners of vehicles and equipment,14.417107,84.03319755
550,"Laborers and freight, stock, and material move...",17.376687,83.73217923
551,Machine feeders and offbearers,42.184821,None
552,"Packers and packagers, hand",56.045849,83.98382359
553,Pumping station operators,3.188332,None
554,Refuse and recyclable material collectors,9.696179,None
555,Mine shuttle car operators,1.366120,None
556,"Tank car, truck, and ship loaders",1.024297,None
557,"Material moving workers, all other",14.785015,None

In [23]:
selected_test.columns = ["Occupation", "Percentage of Women in Field", "Percentage of Men's Earnings Estimate"]
pd.to_numeric([selected_test["Percentage of Women in Field"], selected_test["Percentage of Men\'s Earnings Estimate"]], errors="coerce")
selected_test

,Occupation,Percentage of Women in Field,Percentage of Men's Earnings Estimate
0,Total,43.055084,80.2
1,"Management, Business, Science, and Arts Occupa...",49.004558,72.3
2,"Management, Business, and Financial Occupations",43.496134,75.5
3,Management Occupations,38.784482,76.1
4,Chief executives,23.810727,73.39342915
5,General and operations managers,29.483516,74.63473494
6,Legislators,46.792210,94.87602814
7,Advertising and promotions managers,58.712438,76.8562957
8,Marketing and sales managers,44.895359,68.98449125
9,Public relations and fundraising managers,67.322627,89.57817559
10,Administrative services managers,39.493224,86.2282914
11,Computer and information systems managers,26.825641,89.00671253
12,Financial managers,52.578191,61.77702602
13,Compensation and benefits managers,75.084924,None
14,Human resources managers,61.073074,90.80722409
15,Training and development managers,52.043635,78.51004952
16,Industrial production managers,20.008808,90.69529652
17,Purchasing managers,47.893851,85.07538848
18,"Transportation, storage, and distribution mana...",18.009013,104.7364196
19,"Farmers, ranchers, and other agricultural mana...",11.222768,72.06684048
20,Construction managers,7.836197,86.52565119
21,Education administrators,62.289261,80.25503857
22,Architectural and engineering managers,8.877717,99.96546431
23,Food service managers,44.908029,74.78932419
24,Funeral service managers,27.210884,None
25,Gaming managers,34.554500,93.30792037
26,Lodging managers,52.687602,79.85956632
27,Medical and health services managers,70.984562,76.57110788
28,Natural sciences managers,52.757312,68.65503457
29,Postmasters and mail superintendents,45.586480,93.5691496
...,...,...,...
528,Taxi drivers and chauffeurs,12.118453,87.07518023
529,"Motor vehicle operators, all other",15.031187,None
530,Locomotive engineers and operators,5.097396,None
531,"Railroad brake, signal, and switch operators",6.642274,None
532,Railroad conductors and yardmasters,5.977926,None
533,"Subway, streetcar, and other rail transportati...",12.803394,None
534,Sailors and marine oilers,10.321733,None
535,Ship and boat captains and operators,4.460055,None
536,Ship engineers,10.343688,None
537,Bridge and lock tenders,8.813818,None
538,Parking lot attendants,13.058546,None
539,Automotive and watercraft service attendants,11.907016,None
540,Transportation inspectors,12.593002,None
541,"Transportation attendants, except flight atten...",51.876155,None
542,Other transportation workers,16.978525,None
543,Material Moving Occupations,18.811464,79.2
544,Conveyor operators and tenders,22.136887,None
545,Crane and tower operators,2.824134,None
546,"Dredge, excavating, and loading machine operators",1.402628,None
547,Hoist and winch operators,3.420964,None
548,Industrial truck and tractor operators,7.187780,99.89784863
549,Cleaners of vehicles and equipment,14.417107,84.03319755
550,"Laborers and freight, stock, and material move...",17.376687,83.73217923
551,Machine feeders and offbearers,42.184821,None
552,"Packers and packagers, hand",56.045849,83.98382359
553,Pumping station operators,3.188332,None
554,Refuse and recyclable material collectors,9.696179,None
555,Mine shuttle car operators,1.366120,None
556,"Tank car, truck, and ship loaders",1.024297,None
557,"Material moving workers, all other",14.785015,None

In [27]:
selected_test.isnull().sum()

Occupation                                 0
Percentage of Women in Field               0
Percentage of Men's Earnings Estimate    212
dtype: int64

In [29]:
bls = pd.read_csv("womenstable2formatted.csv")
bls.head()

,Occupation,Number of workers,Median weekly earnings,Standard error of median,Number of workers.1,Median weekly earnings.1,Standard error of median.1,Number of workers.2,Median weekly earnings.2,Standard error of median.2,Percentage of Men's
0,"Total, full-time wage and salary workers","115,567",$886,$2,"51,425",$789,$3,"64,142",$973,$3,81.1
1,"Management, professional, and related occupations","48,808","1,246",4,"25,123","1,078",6,"23,685","1,468",8,73.4
2,"Management, business, and financial operations...","19,863","1,355",6,"9,195","1,168",8,"10,668","1,537",10,76.0
3,Management occupations,"13,477","1,429",10,"5,724","1,236",11,"7,754","1,585",16,78.0
4,Chief executives,"1,098","2,291",23,307,"1,736",96,790,"2,488",90,69.8

In [37]:
bls["Percentage of Men\'s"] = bls["Percentage of Men\'s"].replace({"–": None})
bls_selected = bls[["Occupation", "Percentage of Men\'s"]]
bls_selected

                                            Occupation Percentage of Men's
0             Total, full-time wage and salary workers                81.1
1    Management, professional, and related occupations                73.4
2    Management, business, and financial operations...                76.0
3                               Management occupations                78.0
4                                     Chief executives                69.8
5                      General and operations managers                79.8
6                                          Legislators                None
7                  Advertising and promotions managers                None
8                         Marketing and sales managers                73.5
9            Public relations and fundraising managers                None
10                    Administrative services managers                None
11           Computer and information systems managers                89.9
12                                  Financial managers                70.7
13                  Compensation and benefits managers                None
14                            Human resources managers                75.5
15                   Training and development managers                None
16                      Industrial production managers                82.4
17                                 Purchasing managers                85.9
18   Transportation, storage, and distribution mana...                None
19   Farmers, ranchers, and other agricultural mana...                None
20                               Construction managers                81.9
21                            Education administrators                79.7
22              Architectural and engineering managers                None
23                               Food service managers                76.8
24                            Funeral service managers                None
25                                     Gaming managers                None
26                                    Lodging managers                None
27                Medical and health services managers                77.0
28                           Natural sciences managers                None
29                Postmasters and mail superintendents                None
..                                                 ...                 ...
535             Driver/sales workers and truck drivers                67.4
536                        Taxi drivers and chauffeurs                71.7
537                 Motor vehicle operators, all other                None
538                 Locomotive engineers and operators                None
539       Railroad brake, signal, and switch operators                None
540                Railroad conductors and yardmasters                None
541  Subway, streetcar, and other rail transportati...                None
542                          Sailors and marine oilers                None
543               Ship and boat captains and operators                None
544                                     Ship engineers                None
545                            Bridge and lock tenders                None
546                             Parking lot attendants                None
547       Automotive and watercraft service attendants                None
548                          Transportation inspectors                None
549  Transportation attendants, except flight atten...                None
550                       Other transportation workers                None
551                     Conveyor operators and tenders                None
552                          Crane and tower operators                None
553  Dredge, excavating, and loading machine operators                None
554                          Hoist and winch operators                None
555             Industrial truck and tractor operators                None
556                 Cleaners of vehicles and equipment                None
557  Laborers and freight, stock, and material move...                87.3
558                     Machine feeders and offbearers                None
559                        Packers and packagers, hand                93.8
560                          Pumping station operators                None
561          Refuse and recyclable material collectors                None
562                         Mine shuttle car operators                None
563                  Tank car, truck, and ship loaders                None
564                 Material moving workers, all other                None

[565 rows x 2 columns]

In [38]:
bls_selected.isnull().sum()

Occupation               0
Percentage of Men's    410
dtype: int64

In [39]:
selected_test.isnull().sum()[2] / len(selected_test), bls_selected.isnull().sum()[1] / len(bls_selected)

(0.37992831541218636, 0.72566371681415931)

In [40]:
#Therefore, we'll use the enigma data for percentage by occupation because of less missing values

In [41]:
selected_test.to_csv("occupation_2016.csv")