In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
test = pd.read_csv("City_of_Seattle_Wages__Comparison_by_Gender_-_Discretionary_Pay_Titles_by_Department.csv")
test.head(50)

,DEPARTMENT,DESCR,GENDER DESCR,Admin Support # EE,Admin Support % Gender,Admin Support Avg Hrly,Admin Support Avg Yrs in Current Job,Officials/Admin # EE,Officials/Admin % Gender,Officials/Admin Avg Hrly,...,Service/Maintenance Avg Hrly,Service/Maintenance Avg Yrs in Current Job,Skilled Craft # EE,Skilled Craft % Gender,Skilled Craft Avg Hrly,Skilled Craft Avg Yrs in Current Job,Technicians # EE,Technicians % Gender,Technicians Avg Hrly,Technicians Avg Yrs in Current Job
0,Arts and Cultural Affairs,NaN,Female,2.0,100.0,26.53,NaN,2.0,67.0,49.97,...,27.78,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1,Arts and Cultural Affairs,NaN,Male,0.0,0.0,NaN,NaN,1.0,33.0,51.95,...,20.73,NaN,0.0,NaN,NaN,NaN,1.0,100.0,29.04,NaN
2,Arts and Cultural Affairs,Total Employees,NaN,2.0,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,Arts and Cultural Affairs,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,3.9,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1
4,City Auditor,NaN,Female,0.0,NaN,NaN,NaN,0.0,0.0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
5,City Auditor,NaN,Male,0.0,NaN,NaN,NaN,1.0,100.0,65.26,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
6,City Auditor,Total Employees,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,City Auditor,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,City Budget Office,NaN,Female,1.0,100.0,26.26,NaN,1.0,50.0,73.03,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
9,City Budget Office,NaN,Male,0.0,0.0,NaN,NaN,1.0,50.0,68.27,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
10,City Budget Office,Total Employees,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,City Budget Office,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,7.3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,City Employees Retirement Syst,NaN,Female,6.0,75.0,23.44,NaN,1.0,100.0,81.97,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
13,City Employees Retirement Syst,NaN,Male,2.0,25.0,23.92,NaN,0.0,0.0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
14,City Employees Retirement Syst,Total Employees,NaN,8.0,NaN,NaN,NaN,1.0,NaN,81.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,City Employees Retirement Syst,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,City Light,NaN,Female,132.0,69.0,24.81,NaN,26.0,33.0,58.27,...,25.42,NaN,52.0,10.0,41.84,NaN,40.0,28.0,38.31,NaN
17,City Light,NaN,Male,60.0,31.0,24.83,NaN,52.0,67.0,65.37,...,27.79,NaN,490.0,90.0,41.00,NaN,101.0,72.0,42.98,NaN
18,City Light,Total Employees,NaN,192.0,NaN,NaN,NaN,78.0,NaN,NaN,...,NaN,NaN,542.0,NaN,NaN,NaN,141.0,NaN,NaN,NaN
19,City Light,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,9.7,NaN,NaN,NaN,...,NaN,8.3,NaN,NaN,NaN,6.5,NaN,NaN,NaN,7.1
20,Civil Service Commissions,NaN,Female,0.0,NaN,NaN,NaN,1.0,17.0,5.53,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
21,Civil Service Commissions,NaN,Male,0.0,NaN,NaN,NaN,5.0,83.0,5.53,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
22,Civil Service Commissions,Total Employees,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Civil Service Commissions,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Department of Planning & Dev,NaN,Female,19.0,79.0,24.50,NaN,9.0,35.0,57.45,...,NaN,NaN,0.0,NaN,NaN,NaN,39.0,33.0,32.98,NaN
25,Department of Planning & Dev,NaN,Male,5.0,21.0,24.73,NaN,17.0,65.0,55.24,...,22.56,NaN,0.0,NaN,NaN,NaN,80.0,67.0,39.13,NaN
26,Department of Planning & Dev,Total Employees,NaN,24.0,NaN,NaN,NaN,26.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,119.0,NaN,NaN,NaN
27,Department of Planning & Dev,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,6.2,NaN,NaN,NaN,...,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.4
28,Dept of Finance & Admn Svc,NaN,Female,62.0,83.0,24.62,NaN,21.0,46.0,51.16,...,24.15,NaN,9.0,8.0,32.29,NaN,11.0,44.0,30.78,NaN
29,NaN,NaN,Male,13.0,17.0,25.33,NaN,25.0,54.0,54.88,...,22.42,NaN,97.0,92.0,32.42,NaN,14.0,56.0,33.02,NaN
30,NaN,Total Employees,NaN,75.0,NaN,NaN,NaN,46.0,NaN,NaN,...,NaN,NaN,106.0,NaN,NaN,NaN,25.0,NaN,NaN,NaN
31,NaN,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,NaN,10.9,NaN,NaN,NaN,8.8,NaN,NaN,NaN,12.0
32,Ethics And Elections,NaN,Female,0.0,0.0,NaN,NaN,0.0,0.0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
33,Ethics And Elections,NaN,Male,1.0,100.0,24.35,NaN,1.0,100.0,67.42,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
34,Ethics And Elections,Total Employees,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Ethics And Elections,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Fire Department,NaN,Female,28.0,97.0,24.20,NaN,4.0,20.0,57.35,...,NaN,NaN,0.0,0.0,NaN,NaN,15.0,9.0,42.79,NaN
37,Fire Department,NaN,Male,1.0,3.0,24.35,NaN,16.0,80.0,75.95,...,27.84,NaN,4.0,100.0,48.44,NaN,148.0,44.0,43.65,NaN
38,Fire Department,Total Employees,NaN,29.0,NaN,NaN,NaN,20.0,NaN,NaN,...,NaN,NaN,4.0,NaN,NaN,NaN,163.0,NaN,NaN,NaN
39,Fire Department,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,6.6,NaN,NaN,NaN,...,NaN,3.8,NaN,NaN,NaN,4.3,NaN,NaN,NaN,11.6
40,Hearing Examiner,NaN,Female,2.0,100.0,23.66,NaN,1.0,100.0,72.07,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
41,Hearing Examiner,NaN,Male,0.0,0.0,NaN,NaN,0.0,0.0,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
42,Hearing Examiner,Total Employees,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Hearing Examiner,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,3.7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Housing,NaN,Female,5.0,100.0,23.28,NaN,2.0,50.0,48.48,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN
45,Housing,NaN,Male,0.0,0.0,NaN,NaN,2.0,50.0,56.23,...,NaN,NaN,0.0,NaN,NaN,NaN,7.0,100.0,35.34,NaN
46,Housing,Total Employees,NaN,5.0,NaN,23.28,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN
47,Housing,Ave Yrs in Current Job,NaN,NaN,NaN,NaN,10.3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
48,Human Services,NaN,Female,32.0,84.0,23.31,NaN,15.0,79.0,47.22,...,14.48,NaN,0.0,NaN,NaN,NaN,1.0,100.0,25.77,NaN
49,Human Services,NaN,Male,6.0,16.0,23.19,NaN,4.0,21.0,44.86,...,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN

In [8]:
test.columns

Index(['DEPARTMENT', 'DESCR', 'GENDER DESCR', 'Admin Support # EE',
       'Admin Support % Gender', 'Admin Support Avg Hrly',
       'Admin Support Avg Yrs in Current Job', 'Officials/Admin # EE',
       'Officials/Admin % Gender', 'Officials/Admin Avg Hrly',
       'Officials/Admin Avg Yrs in Current Job', 'Para-Professionals # EE',
       'Para-Professionals % Gender', 'Para-Professionals Avg Hrly',
       'Para-Professionals Avg Yrs in Current Job', 'Professionals # EE',
       'Professionals % Gender', 'Professionals Avg Hrly',
       'Professionals Avg Yrs in Current Job', 'Protected Services # EE',
       'Protected Services % Gender', 'Protected Services Avg Hrly',
       'Protected Services Avg Yrs in Current Job', 'Service/Maintenance # EE',
       'Service/Maintenance % Gender', 'Service/Maintenance Avg Hrly',
       'Service/Maintenance Avg Yrs in Current Job', 'Skilled Craft # EE',
       'Skilled Craft % Gender', 'Skilled Craft Avg Hrly',
       'Skilled Craft Avg Yrs in Current Job', 'Technicians # EE',
       'Technicians % Gender', 'Technicians Avg Hrly',
       'Technicians Avg Yrs in Current Job'],
      dtype='object')

In [10]:
selected_test = test[['DEPARTMENT', 'GENDER DESCR', 'Professionals Avg Hrly', 'Professionals Avg Yrs in Current Job', 'Technicians % Gender', 'Technicians Avg Hrly', 'Technicians Avg Yrs in Current Job']]
selected_test

,DEPARTMENT,GENDER DESCR,Professionals Avg Hrly,Professionals Avg Yrs in Current Job,Technicians % Gender,Technicians Avg Hrly,Technicians Avg Yrs in Current Job
0,Arts and Cultural Affairs,Female,35.00,NaN,0.0,NaN,NaN
1,Arts and Cultural Affairs,Male,32.64,NaN,100.0,29.04,NaN
2,Arts and Cultural Affairs,NaN,NaN,NaN,NaN,NaN,NaN
3,Arts and Cultural Affairs,NaN,NaN,5.2,NaN,NaN,0.1
4,City Auditor,Female,49.67,NaN,NaN,NaN,NaN
5,City Auditor,Male,47.52,NaN,NaN,NaN,NaN
6,City Auditor,NaN,NaN,NaN,NaN,NaN,NaN
7,City Auditor,NaN,NaN,6.5,NaN,NaN,NaN
8,City Budget Office,Female,45.60,NaN,NaN,NaN,NaN
9,City Budget Office,Male,45.70,NaN,NaN,NaN,NaN
10,City Budget Office,NaN,NaN,NaN,NaN,NaN,NaN
11,City Budget Office,NaN,NaN,2.7,NaN,NaN,NaN
12,City Employees Retirement Syst,Female,36.58,NaN,NaN,NaN,NaN
13,City Employees Retirement Syst,Male,46.24,NaN,NaN,NaN,NaN
14,City Employees Retirement Syst,NaN,NaN,NaN,NaN,NaN,NaN
15,City Employees Retirement Syst,NaN,NaN,4.4,NaN,NaN,NaN
16,City Light,Female,42.24,NaN,28.0,38.31,NaN
17,City Light,Male,46.29,NaN,72.0,42.98,NaN
18,City Light,NaN,NaN,NaN,NaN,NaN,NaN
19,City Light,NaN,NaN,5.6,NaN,NaN,7.1
20,Civil Service Commissions,Female,41.71,NaN,NaN,NaN,NaN
21,Civil Service Commissions,Male,NaN,NaN,NaN,NaN,NaN
22,Civil Service Commissions,NaN,NaN,NaN,NaN,NaN,NaN
23,Civil Service Commissions,NaN,NaN,6.9,NaN,NaN,NaN
24,Department of Planning & Dev,Female,41.30,NaN,33.0,32.98,NaN
25,Department of Planning & Dev,Male,44.78,NaN,67.0,39.13,NaN
26,Department of Planning & Dev,NaN,NaN,NaN,NaN,NaN,NaN
27,Department of Planning & Dev,NaN,NaN,5.4,NaN,NaN,5.4
28,Dept of Finance & Admn Svc,Female,40.68,NaN,44.0,30.78,NaN
29,NaN,Male,43.66,NaN,56.0,33.02,NaN
...,...,...,...,...,...,...,...
94,Office of Sustainability & Env,NaN,NaN,NaN,NaN,NaN,NaN
95,Office of Sustainability & Env,NaN,NaN,3.4,NaN,NaN,NaN
96,Parks Department,Female,34.13,NaN,57.0,28.51,NaN
97,Parks Department,Male,35.91,NaN,43.0,33.62,NaN
98,Parks Department,NaN,NaN,NaN,NaN,NaN,NaN
99,Parks Department,NaN,NaN,7.8,NaN,NaN,8.0
100,Personnel Department,Female,39.49,NaN,100.0,26.26,NaN
101,Personnel Department,Male,45.42,NaN,0.0,NaN,NaN
102,Personnel Department,NaN,NaN,NaN,NaN,NaN,NaN
103,Personnel Department,NaN,NaN,5.8,NaN,NaN,16.9
104,Police Department,Female,41.16,NaN,24.0,39.72,NaN
105,Police Department,Male,53.95,NaN,76.0,50.86,NaN
106,Police Department,NaN,NaN,NaN,NaN,NaN,NaN
107,Police Department,NaN,NaN,6.7,NaN,NaN,7.2
108,Seattle Center,Female,37.34,NaN,21.0,29.55,NaN
109,Seattle Center,Male,42.61,NaN,79.0,32.11,NaN
110,Seattle Center,NaN,NaN,NaN,NaN,NaN,NaN
111,Seattle Center,NaN,NaN,7.8,NaN,NaN,8.0
112,Seattle Dept of Transportation,Female,42.51,NaN,32.0,39.30,NaN
113,Seattle Dept of Transportation,Male,44.46,NaN,68.0,39.68,NaN
114,Seattle Dept of Transportation,NaN,NaN,NaN,NaN,NaN,NaN
115,Seattle Dept of Transportation,NaN,NaN,4.7,NaN,NaN,6.3
116,Seattle Public Library,Female,37.45,NaN,21.0,39.62,NaN
117,Seattle Public Library,Male,38.59,NaN,79.0,43.80,NaN
118,Seattle Public Library,NaN,37.42,NaN,NaN,NaN,NaN
119,Seattle Public Library,NaN,NaN,8.4,NaN,NaN,4.5
120,Seattle Public Utilities,Female,43.51,NaN,30.0,37.80,NaN
121,Seattle Public Utilities,Male,45.51,NaN,70.0,37.57,NaN
122,Seattle Public Utilities,NaN,NaN,NaN,NaN,NaN,NaN
123,Seattle Public Utilities,NaN,NaN,6.9,NaN,NaN,6.5